# Generated by Django 4.2.11 on 2024-04-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vara', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.JSONField(null=True),
        ),
    ]
