# Generated by Django 4.2.11 on 2024-04-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vara', '0002_user_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=20)),
                ('jan', models.FloatField()),
                ('feb', models.FloatField()),
                ('march', models.FloatField()),
                ('april', models.FloatField()),
                ('may', models.FloatField()),
                ('june', models.FloatField()),
                ('july', models.FloatField()),
                ('august', models.FloatField()),
                ('sept', models.FloatField()),
                ('oct', models.FloatField()),
                ('nov', models.FloatField()),
                ('dec', models.FloatField()),
            ],
        ),
    ]
