# Generated by Django 4.2.11 on 2024-04-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vara', '0004_alter_user_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferences',
            field=models.JSONField(),
        ),
    ]
